#!/usr/bin/env python3
# Retina Rave — © 2026 Thomas Kraft. Licensed under the Retina Rave License (MIT + the Guest-List Clause):
# use it at a party and Toma gets in free. Full text: https://retinarave.com/LICENSE and ./LICENSE in the repo.
# Source: https://github.com/tbkraf08/RetinaRave
"""The real-music WINDOWS (DECISIONS §109): per library track, the frame-addressed shots tools/real-md5.sh takes and the 60 s
window tools/real-rulers.sh runs, derived from the track's OWN structure in tools/truth/<Track>.json (trackmap.py) the way
§104 chose SeeYouDrop's (intro f602@at=0, groove f602@at=25, drop1 f1958@at=25, build f1202@at=80, drop2 f1538@at=80):

    python3 tools/truth/windows.py            -> tools/truth/windows.json (committed) + the table on stdout

Per track, one RUN per `at` (a cold deterministic start there, HARNESS "File source"; windows sharing an `at` share the run), its shots addressed by __FRAME
(heardT = at + (frame − 2)/60, so frame = 2 + round((t − at)·60)):
  intro   at 0, t 10                         the first ten seconds
  groove  at L, t L+10                       L = summary.loudest30_from (the loudest 30 s); when L < 15 s the groove IS the intro,
                                             so L = the first section boundary ≥ 20 s instead
  quiet   at Q, t Q+10                       Q = the start of the sparsest 10 s (the lowest onset density — low + click + mid_on +
                                             high_on per second over the 5 s slices — from 10 s on, not inside another window)
  dropN   at max(0, ⌊d⌋ − 25): build t d−5, drop t d     the first two `drops` (bar-pinned, DROP_MIN); a track with no drop
                                             (CyborgNinja) takes its first two section boundaries ≥ 20 s as boundaryN instead
  rulers  from max(0, L − 20) to from + 60   the continuity / luminance window: the approach to the loudest 30 s and the 30 s itself
The pad take (rec, FLUID-DIAG-2026-10-09, 24.4 s, &map=0 only): intro at 0 t 10 and chords t 20 (§108's 19–21 s attacks), rulers 0 → 24.4.
`gate` false (Malicious, NO_GATE) = recorded and swept for the record, never a FAIL and never asserted.
"""
import json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
TRACKS = ['Comptine', 'CyborgNinja', 'IBelongHere', 'Malicious', 'SeeYouDrop', 'Vienna', 'WhoLikesToParty']
# `gate: false` — in the sweeps and the traces for the record, but NOT a FAIL rule and NOT asserted by the node tests (§109: the user,
# 2026-10-09: "can ignore malicious until I validate the ruler" — the map's sub ruler on Malicious is pending his validation)
NO_GATE = {'Malicious'}
FPS = 60

def frame(at, t):
    return 2 + int(round((t - at) * FPS))

def windows(track):
    d = json.load(open(os.path.join(HERE, track + '.json')))
    s, secs, drops = d['summary'], d['sections'], d.get('drops') or []
    dur = s['seconds']
    runs = []   # [{at, shots: [{name, t, f}]}]
    runs.append({'at': 0, 'shots': [{'name': 'intro', 't': 10.0}]})
    L = s['loudest30_from']
    if L < 15:
        L = next((x['t0'] for x in secs if x['t0'] >= 20), 20.0)
    L = float(int(L))
    runs.append({'at': L, 'shots': [{'name': 'groove', 't': L + 10}]})
    # the sparsest 10 s from the 5 s slices' onset densities (per second), outside the intro / groove windows
    sl = d['slices']['5']
    taken = [(0, 10), (L, L + 10)]
    best, Q = None, None
    for i in range(len(sl) - 1):
        t0 = sl[i]['t']
        if t0 < 10 or t0 + 10 > dur - 5: continue
        if any(t0 < b and t0 + 10 > a for a, b in taken): continue
        dens = sum(sl[j]['low'] + sl[j]['click'] + sl[j]['mid_on'] + sl[j]['high_on'] for j in (i, i + 1)) / 2
        if best is None or dens < best: best, Q = dens, t0
    if Q is not None:
        runs.append({'at': float(Q), 'shots': [{'name': 'quiet', 't': Q + 10}]})
    hits = [(x, 'drop') for x in drops[:2]]
    if not hits:
        hits = [(x['t0'], 'boundary') for x in secs if x['t0'] >= 20][:2]
    for k, (t, kind) in enumerate(hits):
        at = float(max(0, math.floor(t) - 25))
        runs.append({'at': at, 'shots': [{'name': 'build%d' % (k + 1), 't': round(t - 5, 3)}, {'name': '%s%d' % (kind, k + 1), 't': round(t, 3)}]})
    merged = {}   # one run per `at`: Comptine's drop 1 (21.5 s) and IBelongHere's (15.9 s) share the intro's run at 0
    for r in runs:
        merged.setdefault(r['at'], []).extend(r['shots'])
    runs = [{'at': at, 'shots': sorted(sh, key=lambda x: x['t'])} for at, sh in sorted(merged.items())]
    for r in runs:
        for sh in r['shots']:
            sh['f'] = frame(r['at'], sh['t'])
    rf = float(max(0, int(L) - 20))
    return {'track': track, 'seconds': dur, 'bpm': s['bpm'], 'loudest30_from': s['loudest30_from'], 'drops': drops,
            'runs': runs, 'rulers': {'from': rf, 'to': rf + 60}, 'gate': track not in NO_GATE}

out = {'note': 'generated by tools/truth/windows.py (DECISIONS §109) from tools/truth/<Track>.json; frame = 2 + round((t - at)*60)', 'tracks': {}}
for t in TRACKS:
    if not os.path.exists(os.path.join(HERE, t + '.json')):
        print('no truth for', t, '— python3 tools/truth/trackmap.py', t, '--grains=8,5,3,2,1,0.569,0.224', file=sys.stderr); continue
    out['tracks'][t] = windows(t)
out['tracks']['rec'] = {'track': 'rec', 'seconds': 24.4, 'bpm': None, 'loudest30_from': None, 'drops': [], 'map0only': True, 'gate': True,
                        'runs': [{'at': 0, 'shots': [{'name': 'intro', 't': 10.0, 'f': frame(0, 10.0)}, {'name': 'chords', 't': 20.0, 'f': frame(0, 20.0)}]}],
                        'rulers': {'from': 0, 'to': 24.4}}
json.dump(out, open(os.path.join(HERE, 'windows.json'), 'w'), indent=1)
for t, w in out['tracks'].items():
    shots = ' · '.join('%s f%d@at=%g (%.1f s)' % (sh['name'], sh['f'], r['at'], sh['t']) for r in w['runs'] for sh in r['shots'])
    print('%-16s %6.1f s  bpm %-6s rulers %g-%g | %s' % (t, w['seconds'], w['bpm'], w['rulers']['from'], w['rulers']['to'], shots))
