#!/bin/bash
# v0.2 acceptance sweep -> tools/accept/v0.2/. Run with GPU=1. Prints one line per check; grep FAIL. The real-path and
# bundle lines also count cdp's [EXC] lines (uncaught exceptions never reach CARD.ERRS — the bundle was dead for months
# of commits with errs [] until §11 counted them).
cd "$(dirname "$0")/.." || exit 1
export OUT=tools/accept/v0.2; mkdir -p $OUT
echo "== check.js";      node tools/check.js || echo "FAIL check.js"
echo "== math tests";    node tools/test_baby.js | tail -1; node tools/test_misi.js | tail -1; node tools/test_hopf.js | tail -1; node tools/test_tempo.js | tail -1; node tools/test_director.js | tail -1
echo "== lines smoke";    node tools/lines-smoke.js | tail -1
echo "== parity fake";   node tools/parity.js fake | grep -E "parity|MISMATCH|max \|diff\|" || echo "FAIL parity fake"
echo "== parity real";   node tools/parity.js real | tail -1
MON=$(grep -v '^//' tools/monitor.js | tr '\n' ' ' | sed 's/"/\\"/g')
echo "== monitor 60 s";  node tools/cdp.js 'test&fake=0' "[{\"wait\":1500},{\"eval\":\"$MON;'ok'\"},{\"wait\":60000},{\"eval\":\"'MON '+JSON.stringify({n:MON.n,fast:MON.fast,viol:MON.viol,errs:CARD.ERRS,bad:CARD.nonFinite()})\"}]" | grep EVAL | sed 's/.*=> //'
echo "== scenes on #test (T6 / T14)"
IDS=$(grep -ho "^  id: [0-9]*" assets/scenes/*/index.js | grep -o "[0-9]*" | sort -n)
for i in $IDS; do
  node tools/cdp.js "test&scene=$i" "[{\"wait\":6000},{\"eval\":\"'scene $i ERRS '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())+' | '+(CARD.REG[$i]?CARD.REG[$i].scene.name:'?')\"},{\"shot\":\"s$i-t6\"},{\"wait\":8200},{\"shot\":\"s$i-t14\"}]" | grep EVAL | sed 's/.*=> //'
done
# v0.2 §13/§15: a scene that samples the hist texture must shoot the same CLOCK=1 frame with the whole-texture upload (&histfull=1) and the row-delta upload
for d in $(grep -l "engineTex.hist" assets/scenes/*/index.js); do i=$(grep -o "^  id: [0-9]*" $d | grep -o "[0-9]*"); n=$(basename $(dirname $d))
  CLOCK=1 node tools/cdp.js "test&scene=$i" '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"hist-s'$i'-f360"},{"until":"window.__FRAME>=840"},{"shot":"hist-s'$i'-f840"}]' > /dev/null
  CLOCK=1 node tools/cdp.js "test&scene=$i&histfull=1" '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"hist-s'$i'-f360-full"},{"until":"window.__FRAME>=840"},{"shot":"hist-s'$i'-f840-full"}]' > /dev/null
  A=$(md5sum $OUT/hist-s$i-f360.jpg | cut -c1-32); B=$(md5sum $OUT/hist-s$i-f360-full.jpg | cut -c1-32); C=$(md5sum $OUT/hist-s$i-f840.jpg | cut -c1-32); D=$(md5sum $OUT/hist-s$i-f840-full.jpg | cut -c1-32)
  [ "$A" = "$B" ] && [ "$C" = "$D" ] && echo "hist rows == full on $n (id $i): f360 $A f840 $C" || echo "FAIL hist rows != full on $n (id $i): f360 $A/$B f840 $C/$D"
done
# v0.2 §16: FEIGEN's steady-state cost at the deepest level, tier 3, must stay at or under NAV's (interleaved in the same page; 1.5× covers the load drift) and under 2.9 ms; feigen-bench.sh writes feigen-bench-accept.txt
echo "== feigen cost";   R=$(tools/feigen-bench.sh accept 3.6 2>/dev/null | grep "^feig=3.6: L .* feigen" | head -1); F=$(echo "$R" | sed 's/.* feigen \([0-9.]*\) ms.*/\1/'); N=$(echo "$R" | sed 's/.* nav \([0-9.]*\) ms.*/\1/'); echo "$R" | cut -c1-120
[ -n "$F" ] && awk -v f="$F" -v n="$N" 'BEGIN{lim=(n*1.5>2.9)?n*1.5:2.9; if (f<=lim) print "feigen L3.6 steady " f " ms <= " lim " (nav " n ")"; else print "FAIL feigen L3.6 steady " f " ms > " lim " (nav " n ")"}' || echo "FAIL feigen-bench.sh gave no L3.6 line"
echo "== transition";  MD5=a6e2b8cdcc47316cebb04f5529a26b06   # mixs, director-blind (v0.2 §15): scene 0 forced, released at frame 120 with goScene(3), shot at 178 (m .499), GPU=1 1280×720. v3's crossfade byte-identical since §11; re-based from the frame-290 director pick (4ac523e9…) when FEIGEN's registration changed that pick — same pixels with FEIGEN unregistered (DECISIONS §15)
TR='{"until":"window.CARD"},{"until":"window.__FRAME>=120"},{"eval":"CARD.SC.forced=-1;CARD.goScene(3,false);CARD.SC.next"},{"until":"window.__FRAME>=178"}'
CLOCK=1 node tools/cdp.js 'test&scene=0&trans=mixs' "[$TR,{\"shot\":\"trans-mixs-0-3-f178\"}]" > /dev/null; M=$(md5sum $OUT/trans-mixs-0-3-f178.jpg | cut -c1-32); [ "$M" = "$MD5" ] && echo "mixs 0→3 f178 md5 $M = recorded" || echo "FAIL mixs 0→3 f178 md5 $M != recorded $MD5"
CLOCK=1 node tools/cdp.js 'test&scene=0&trans=morph' "[$TR,{\"shot\":\"trans-morph-0-3-f178\"},{\"eval\":\"'MORPH 0→3 f178 '+JSON.stringify({sc:[CARD.SC.cur,CARD.SC.next,+CARD.SC.m.toFixed(3)],errs:CARD.ERRS,bench:CARD.benchTransition(300)})\"}]" | grep "EVAL.*MORPH" | sed 's/.*=> //'
python3 tools/montage.py $OUT/montage-trans.jpg 2 $OUT/trans-mixs-0-3-f178.jpg $OUT/trans-morph-0-3-f178.jpg $OUT/trans-mixs-0-2-f178.jpg $OUT/trans-morph-0-2-f178.jpg $OUT/trans-mixs-1-3-f178.jpg $OUT/trans-morph-1-3-f178.jpg $OUT/trans-mixs-5-0-f178.jpg $OUT/trans-morph-5-0-f178.jpg 2>/dev/null && echo "montage $OUT/montage-trans.jpg"
echo "== help"           # v0.2 §12: two shots with the help open (NAV f120, TORUS f360 — the fake timeline's first switch is at 233), the cast scrolled, coverage by eval, ticks hidden/open, the real path with the help opened and closed
CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"key":"h"},{"until":"window.__FRAME>=120"},{"shot":"help-s0-f120"},{"until":"window.__FRAME>=360"},{"shot":"help-s3-f360"},{"eval":"document.getElementById('"'"'help'"'"').scrollTop=1e5;'"'"'help cast shot scrolled to '"'"'+document.getElementById('"'"'help'"'"').scrollTop"},{"shot":"help-cast"},{"eval":"(function(){var out=[],ok=0,n=0,all=Object.keys(CARD.FEATS).filter(function(k){return CARD.FEATS[k].kind!==\"internal\"}).length,rows=0,uniq=0;for(var i=0;i<CARD.REG.length;i++){var E=CARD.REG[i];if(!E)continue;n++;CARD.goScene(E.id,true);var t=CARD.HELP.rows(true),r=CARD.HELP.rows(),f=E.scene.feats;rows=r.length;uniq=new Set(r).size;if(t.slice().sort().join()===f.slice().sort().join())ok++;else out.push(\"id \"+E.id+\" top!=feats\")}return \"help fields \"+rows+\"/\"+all+\" (unique \"+uniq+\") · top table = feats on \"+ok+\"/\"+n+\" ids\"+(out.length?\" FAIL \"+out.join(\",\"):\"\")})()"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"'
CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"until":"window.__FRAME>=600"},{"eval":"'"'"'help ticks hidden '"'"'+CARD.HELP.ticks+'"'"' (600 frames, want 0)'"'"'"},{"key":"h"},{"until":"window.__FRAME>=1200"},{"eval":"'"'"'help ticks open '"'"'+CARD.HELP.ticks+'"'"' (600 frames, want 100) errs '"'"'+JSON.stringify(CARD.ERRS)"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"'
R=$(NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"click":[695,440]},{"wait":3000},{"key":"h"},{"wait":1500},{"shot":"help-real"},{"key":"Escape"},{"wait":1500},{"eval":"'"'"'HELP real '"'"'+JSON.stringify({on:CARD.HELP.on,ticks:CARD.HELP.ticks,bad:CARD.nonFinite(),errs:CARD.ERRS})"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions with the help open"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
echo "== real start path"
R=$(NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"shot":"real-landing"},{"click":[695,440]},{"wait":4000},{"eval":"'"'"'REAL '"'"'+JSON.stringify({mode:CARD.ENGINE.AU.mode,bad:CARD.nonFinite(),errs:CARD.ERRS,glerr:CARD.glerr})"},{"shot":"real-4s"},{"wait":20000},{"eval":"'"'"'REAL24 '"'"'+JSON.stringify({bad:CARD.nonFinite(),errs:CARD.ERRS,switched:CARD.SC.hist.length>1})"},{"shot":"real-24s"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
echo "== bundle";        node tools/bundle.js && R=$(FILE=$PWD/dist/eigenwobble.html NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"click":[695,440]},{"wait":3000},{"key":"h"},{"wait":1500},{"key":"Escape"},{"wait":25500},{"eval":"'"'"'BUNDLE 30s '"'"'+JSON.stringify({bad:CARD.nonFinite(),errs:CARD.ERRS,mode:CARD.ENGINE.AU.mode,hop:CARD.ENGINE.tex.hop,switched:CARD.SC.hist.length>1,help:[CARD.HELP.on,CARD.HELP.ticks]})"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions in the bundle"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
python3 tools/montage.py $OUT/montage-scenes.jpg 2 $OUT/s*-t6.jpg $OUT/s*-t14.jpg 2>/dev/null && echo "montage $OUT/montage-scenes.jpg"
