# Acceptance sweep -> tools/accept/${ACC:-v0.9}/ (earlier sweeps stay in tools/accept/v0.2/, v0.3/, v0.4/). Run with GPU=1. Prints one line per check; grep FAIL. The real-path and
# Acceptance sweep -> tools/accept/${ACC:-v0.9}/ (earlier sweeps stay in tools/accept/v0.2/, v0.3/). Run with GPU=1. Prints one line per check; grep FAIL. The real-path and
# bundle lines also count cdp's [EXC] lines (uncaught exceptions never reach CARD.ERRS — the bundle was dead for months
# of commits with errs [] until §11 counted them).
cd "$(dirname "$0")/.." || exit 1
export FORCE_COLOR=0 NO_COLOR=1   # v0.27: node colours util.inspect output; the params block parsed "\e[33m0.4\e[39m" as a number
export OUT=tools/accept/${ACC:-v0.9}; mkdir -p $OUT
echo "== check.js";      node tools/check.js || echo "FAIL check.js"
echo "== math tests";    node tools/test_baby.js | tail -1; node tools/test_misi.js | tail -1; node tools/test_hopf.js | tail -1; node tools/test_tempo.js | tail -1; node tools/test_director.js | tail -1; node tools/test_oklab.js | tail -1
echo "== lines smoke";    node tools/lines-smoke.js | tail -1
echo "== oklch smoke";    node tools/oklch-smoke.js | tail -1
echo "== chain smoke";    node tools/chain-smoke.js | tail -1
echo "== parity fake";   node tools/parity.js fake | grep -E "parity|MISMATCH|max \|diff\|" || echo "FAIL parity fake"
echo "== parity real";   node tools/parity.js real | tail -1
MON=$(grep -v '^//' tools/monitor.js | tr '\n' ' ' | sed 's/"/\\"/g')
echo "== monitor 60 s";  node tools/cdp.js 'test&fake=0' "[{\"wait\":1500},{\"eval\":\"$MON;'ok'\"},{\"wait\":60000},{\"eval\":\"'MON '+JSON.stringify({n:MON.n,fast:MON.fast,viol:MON.viol,errs:CARD.ERRS,bad:CARD.nonFinite()})\"}]" | grep EVAL | sed 's/.*=> //'
echo "== scenes on #test (T6 / T14)"
IDS=$(grep -ho "^  id: [0-9]*" assets/scenes/*/index.js | grep -o "[0-9]*" | sort -n)
for i in $IDS; do
  node tools/cdp.js "test&scene=$i" "[{\"wait\":6000},{\"eval\":\"'scene $i ERRS '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())+' | '+(CARD.REG[$i]?CARD.REG[$i].scene.name:'?')\"},{\"shot\":\"s$i-t6\"},{\"wait\":8200},{\"shot\":\"s$i-t14\"}]" | grep EVAL | sed 's/.*=> //'
done
# v0.2 §13/§15: a scene that samples the hist texture must shoot the same CLOCK=1 frame with the whole-texture upload (&histfull=1) and the row-delta upload
for d in $(grep -l "engineTex.hist" assets/scenes/*/index.js); do i=$(grep -o "^  id: [0-9]*" $d | grep -o "[0-9]*"); n=$(basename $(dirname $d))
  CLOCK=1 node tools/cdp.js "test&scene=$i" '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"hist-s'$i'-f360"},{"until":"window.__FRAME>=840"},{"shot":"hist-s'$i'-f840"}]' > /dev/null
  CLOCK=1 node tools/cdp.js "test&scene=$i&histfull=1" '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"hist-s'$i'-f360-full"},{"until":"window.__FRAME>=840"},{"shot":"hist-s'$i'-f840-full"}]' > /dev/null
  A=$(md5sum $OUT/hist-s$i-f360.jpg | cut -c1-32); B=$(md5sum $OUT/hist-s$i-f360-full.jpg | cut -c1-32); C=$(md5sum $OUT/hist-s$i-f840.jpg | cut -c1-32); D=$(md5sum $OUT/hist-s$i-f840-full.jpg | cut -c1-32)
  [ "$A" = "$B" ] && [ "$C" = "$D" ] && echo "hist rows == full on $n (id $i): f360 $A f840 $C" || echo "FAIL hist rows != full on $n (id $i): f360 $A/$B f840 $C/$D"
done
# v0.2 §16: FEIGEN's steady-state cost at the deepest level, tier 3, must stay at or under NAV's (interleaved in the same page; 1.5× covers the load drift) and under 2.9 ms; feigen-bench.sh writes feigen-bench-accept.txt
echo "== feigen cost";   R=$(tools/feigen-bench.sh accept 3.6 2>/dev/null | grep "^feig=3.6: L .* feigen" | head -1); F=$(echo "$R" | sed 's/.* feigen \([0-9.]*\) ms.*/\1/'); N=$(echo "$R" | sed 's/.* nav \([0-9.]*\) ms.*/\1/'); echo "$R" | cut -c1-120
[ -n "$F" ] && awk -v f="$F" -v n="$N" 'BEGIN{lim=(n*1.5>2.9)?n*1.5:2.9; if (f<=lim) print "feigen L3.6 steady " f " ms <= " lim " (nav " n ")"; else print "FAIL feigen L3.6 steady " f " ms > " lim " (nav " n ")"}' || echo "FAIL feigen-bench.sh gave no L3.6 line"
echo "== transition";  MD5=f0c9d637cfba1de4a67c6e651f27a8f2   # mixs, director-blind, re-based at v0.9 (§41: v0.8.1's core/hud.js + harness.js moved it to f0c9d637… — the user tagged v0.8.1 on a look, no sweep; proven the same before and after the POLYTOPE merge on 753f985 vs de6a5fe; 641f6633… was the v0.7–v0.8 value), re-based when TORUS2 took id 3 (v0.7 §37: the 0→3 fade lands on TORUS2; 5892ddc5… with TORUS at 3), before that re-based for the v2 colour default (v0.3 §26; 425a66e5… under the §24/§25 OKLCH default, a6e2b8cd… on the v0.2 chain, v0.2 §15): scene 0 forced, released at frame 120 with goScene(3), shot at 178 (m .499), GPU=1 1280×720. v3's crossfade byte-identical since §11; re-based from the frame-290 director pick (4ac523e9…) when FEIGEN's registration changed that pick — same pixels with FEIGEN unregistered (DECISIONS §15)
TR='{"until":"window.CARD"},{"until":"window.__FRAME>=120"},{"eval":"CARD.SC.forced=-1;CARD.goScene(3,false);CARD.SC.next"},{"until":"window.__FRAME>=178"}'
CLOCK=1 node tools/cdp.js 'test&scene=0&trans=mixs' "[$TR,{\"shot\":\"trans-mixs-0-3-f178\"}]" > /dev/null; M=$(md5sum $OUT/trans-mixs-0-3-f178.jpg | cut -c1-32); [ "$M" = "$MD5" ] && echo "mixs 0→3 f178 md5 $M = recorded" || echo "FAIL mixs 0→3 f178 md5 $M != recorded $MD5"
CLOCK=1 node tools/cdp.js 'test&scene=0&trans=morph' "[$TR,{\"shot\":\"trans-morph-0-3-f178\"},{\"eval\":\"'MORPH 0→3 f178 '+JSON.stringify({sc:[CARD.SC.cur,CARD.SC.next,+CARD.SC.m.toFixed(3)],errs:CARD.ERRS,bench:CARD.benchTransition(300)})\"}]" | grep "EVAL.*MORPH" | sed 's/.*=> //'
python3 tools/montage.py $OUT/montage-trans.jpg 2 $OUT/trans-mixs-0-3-f178.jpg $OUT/trans-morph-0-3-f178.jpg $OUT/trans-mixs-0-2-f178.jpg $OUT/trans-morph-0-2-f178.jpg $OUT/trans-mixs-1-3-f178.jpg $OUT/trans-morph-1-3-f178.jpg $OUT/trans-mixs-5-0-f178.jpg $OUT/trans-morph-5-0-f178.jpg 2>/dev/null && echo "montage $OUT/montage-trans.jpg"
echo "== hidden tab"     # v0.3 resume-hold: hide the page 15 s (a second tab activated), back → the first 60 frames fire no onset/drop/surprise, glitch 0, hit 0 (HARNESS "Hidden tab")
R=$(node tools/cdp.js 'test&fake=0&scene=6' '[{"until":"window.CARD"},{"wait":1000},{"eval":"fetch('"'"'/tools/probe.js'"'"').then(r=>r.text()).then(eval).then(()=>PROBE.start())"},{"wait":8000},{"tab":"about:blank"},{"activate":"tab"},{"wait":15000},{"activate":"main"},{"wait":3000},{"eval":"(function(){var b=PROBE.ev.filter(function(e){return e.k===\"back\"}).pop()||{t:1e9};var fr=PROBE.frames.filter(function(f){return f.t>=b.t}).slice(0,60);var r={n:fr.length,onsets:fr.filter(function(f){return f.o}).length,surprise:fr.filter(function(f){return f.s}).length,drops:PROBE.ev.filter(function(e){return e.k===\"drop\"&&e.t>=b.t}).length,gmax:Math.max.apply(null,fr.map(function(f){return f.g})),hitmax:Math.max.apply(null,fr.map(function(f){return f.hit})),resumeAt:+CARD.ENGINE.resumeAt.toFixed(1),errs:CARD.ERRS};return (r.n===60&&r.onsets+r.surprise+r.drops===0&&r.gmax===0&&r.hitmax===0&&r.resumeAt>0?\"hidden tab back \":\"FAIL hidden tab back \")+JSON.stringify(r)})()"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"' | sed 's/\\//g'); echo "$R"
echo "== hidden worklet" # v0.3 §26 audit: the same on the worklet path (synapse's dnb synth, hidden 20 s at 15 s): the 150 frames back fire no surprise and the raw surprisal stays under 1.4 (before the follower snap it ramped 0.1 → 1.5 and a surprise fired at the hold's end); the demo's own surprise at ~43 s is outside the window
R=$(node tools/cdp.js 'test&fake=0&demo=dnb&scene=1' '[{"until":"window.CARD"},{"wait":1000},{"eval":"fetch('"'"'/tools/probe.js'"'"').then(r=>r.text()).then(eval).then(()=>PROBE.start())"},{"wait":14000},{"tab":"about:blank"},{"activate":"tab"},{"wait":20000},{"activate":"main"},{"wait":3000},{"eval":"(function(){var b=PROBE.ev.filter(function(e){return e.k===\"back\"}).pop()||{t:1e9};var fr=PROBE.frames.filter(function(f){return f.t>=b.t}).slice(0,150);return JSON.stringify({n:fr.length,surprise:fr.filter(function(f){return f.s}).length,drops:PROBE.ev.filter(function(e){return e.k===\"drop\"&&e.t>=b.t}).length,srMax:+Math.max.apply(null,fr.map(function(f){return f.sr})).toFixed(2),hop:CARD.ENGINE.tex.hop,resumeAt:+CARD.ENGINE.resumeAt.toFixed(1)})})()"}]' | grep EVAL | tail -1 | sed 's/.*=> //'); echo "$R"; echo "$R" | tr -d '\\' | grep -q '"n":150,"surprise":0,"drops":0,"srMax":\(0\|1\.[0-3]\)' && echo "hidden worklet: 150 frames back, 0 surprise, srMax < 1.4" || echo "FAIL hidden worklet: $R"
echo "== routes"         # v0.4: the node smokes; the view path is exact (an identity route leaves FEIGEN's f360 md5 = the reference, a real route moves it); the manual post the same way (the v2 default's own bloom thr = identical, bloom off moves it); the panel opened (key p) then closed before the shot leaves the canvas md5 identical; a panel-open shot for the eyes
node tools/route-smoke.js | tail -1; node tools/manual-smoke.js | tail -1
REF6=$(grep "s6-f360" tools/accept/v0.7/scene-md5-v07.txt | cut -c1-32)
for r in "route-id:route=feigen.bass=bass:same" "route-hi:route=feigen.bass=high:diff" "post-same:post=feigen.bloom.thr=0.3:same" "post-off:post=feigen.bloom.thr=2:diff"; do t=${r%%:*}; q=${r#*:}; q=${q%:*}; want=${r##*:}
  CLOCK=1 node tools/cdp.js "test&scene=6&$q" "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=360\"},{\"shot\":\"$t-s6-f360\"}]" > /dev/null; M=$(md5sum $OUT/$t-s6-f360.jpg | cut -c1-32)
  if [ "$want" = same ]; then [ "$M" = "$REF6" ] && echo "$t: s6 f360 md5 = reference ($M)" || echo "FAIL $t: s6 f360 md5 $M != reference $REF6"; else [ "$M" != "$REF6" ] && echo "$t: s6 f360 md5 $M != reference (moved, as it must)" || echo "FAIL $t: s6 f360 md5 did not move"; fi
done
R=$(CLOCK=1 node tools/cdp.js 'test&scene=6' '[{"until":"window.CARD"},{"key":"p"},{"until":"window.__FRAME>=300"},{"eval":"'"'"'panel open: on '"'"'+CARD.HELP.on+'"'"' E '"'"'+!!document.getElementById('"'"'helpE'"'"')+'"'"' n '"'"'+CARD.ROUTE.n+'"'"' ticks '"'"'+CARD.HELP.ticks"},{"key":"Escape"},{"until":"window.__FRAME>=360"},{"shot":"panel-closed-s6-f360"}]'); echo "$R" | grep EVAL | sed 's/.*=> //' | tr -d '"'; M=$(md5sum $OUT/panel-closed-s6-f360.jpg | cut -c1-32); [ "$M" = "$REF6" ] && echo "panel opened then closed: s6 f360 md5 = reference" || echo "FAIL panel opened then closed: s6 f360 md5 $M != $REF6"
CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"key":"p"},{"until":"window.__FRAME>=120"},{"shot":"panel-s0-f120"},{"eval":"'"'"'panel shot: scrollTop '"'"'+document.getElementById('"'"'help'"'"').scrollTop+'"'"' rows '"'"'+CARD.HELP.rows().length+'"'"' errs '"'"'+JSON.stringify(CARD.ERRS)"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"'
# v0.4.1 panel-legibility: a preview is a route for 2 s of help ticks then the previous route back, storage untouched; Escape mid-preview puts it back at once (closeE); force/release move MANUAL.scene
R=$(CLOCK=1 node tools/cdp.js 'test&scene=6&route=feigen.bass=centroid*1.5' '[{"until":"window.CARD"},{"key":"p"},{"until":"window.__FRAME>=120"},{"eval":"document.getElementById('"'"'pe-p1-feigen-bass'"'"').click();1"},{"until":"window.__FRAME>=150"},{"eval":"'"'"'PREVIEW f150 '"'"'+CARD.ROUTES.feigen.bass.src+'"'"' c '"'"'+CARD.ROUTES.feigen.bass.c"},{"until":"window.__FRAME>=300"},{"eval":"'"'"'PREVIEW f300 '"'"'+CARD.ROUTES.feigen.bass.src+'"'"' k '"'"'+CARD.ROUTES.feigen.bass.k+'"'"' n '"'"'+CARD.ROUTE.n+'"'"' store '"'"'+localStorage.getItem('"'"'ew.routes.v1'"'"')"},{"eval":"document.getElementById('"'"'pe-p0-feigen-bass'"'"').click();1"},{"until":"window.__FRAME>=310"},{"key":"Escape"},{"until":"window.__FRAME>=320"},{"eval":"'"'"'CLOSE f320 '"'"'+CARD.ROUTES.feigen.bass.src+'"'"' help '"'"'+CARD.HELP.on"}]'); echo "$R" | grep EVAL | sed 's/.*=> //' | tr -d '"'
echo "$R" | grep -q "PREVIEW f150 const c 1" && echo "$R" | grep -q "PREVIEW f300 centroid k 1.5 n 1 store null" && echo "$R" | grep -q "CLOSE f320 centroid help false" && echo "preview: const at f150, centroid*1.5 back at f300, storage null, Escape mid-preview restores" || echo "FAIL preview sequence"
R=$(CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"key":"p"},{"until":"window.__FRAME>=120"},{"eval":"document.getElementById('"'"'pe-force'"'"').click();'"'"'FORCE '"'"'+(CARD.MANUAL.scene===CARD.SC.logical)+'"'"' '"'"'+document.getElementById('"'"'pe-force-line'"'"').textContent.slice(0,20)"},{"eval":"document.getElementById('"'"'pe-release'"'"').click();'"'"'RELEASE '"'"'+CARD.MANUAL.scene"}]'); echo "$R" | grep EVAL | sed 's/.*=> //' | tr -d '"'; echo "$R" | grep -q "FORCE true" && echo "$R" | grep -q "RELEASE -1" && echo "force/release: ok" || echo "FAIL force/release"
echo "== params"         # v0.5: the node smoke; a scene's parameters = from(view) exactly while unrouted (paramsOf == derived); a param route moves FEIGEN's f360 md5 and lo != hi; the panel's parameters table sets one by eval, previews hi for 2 s of ticks, storage untouched under #test
node tools/param-smoke.js | tail -1
P=$(node -e "import('./assets/scenes/feigen/index.js').then(m=>console.log(Object.keys(m.default.params||{})[0]||''))"); LO=$(node -e "import('./assets/scenes/feigen/index.js').then(m=>console.log(m.default.params.$P.range[0]))"); HI=$(node -e "import('./assets/scenes/feigen/index.js').then(m=>console.log(m.default.params.$P.range[1]))")
[ -n "$P" ] && echo "params: FEIGEN's first parameter is $P [$LO, $HI]" || echo "FAIL params: FEIGEN declares no params"
R=$(CLOCK=1 node tools/cdp.js 'test&scene=6' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=360\"},{\"eval\":\"var P=CARD.paramsOf('feigen'),ok=Object.keys(P).every(function(k){return P[k]===CARD.derived('feigen',k)&&isFinite(P[k])});'IDENT '+ok+' n '+Object.keys(P).length+' proutes '+CARD.PROUTE.n+' deps '+JSON.stringify(CARD.paramDeps('feigen','$P'))\"}]" | grep EVAL | sed 's/.*=> //' | tr -d '"'); echo "$R" | grep -q "^IDENT true n [1-9]" && echo "$R" | grep -q "proutes 0" && echo "params identity: $R" || echo "FAIL params identity: $R"
for r in "param-src:param=feigen.$P=centroid*1.5:diff" "param-lo:param=feigen.$P=c:$LO:diff" "param-hi:param=feigen.$P=c:$HI:diff"; do t=${r%%:*}; q=${r#*:}; q=${q%:*}
  CLOCK=1 node tools/cdp.js "test&scene=6&$q" "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=360\"},{\"shot\":\"$t-s6-f360\"},{\"eval\":\"'n '+CARD.PROUTE.n\"}]" | grep -q "EVAL.*n 1" || echo "FAIL $t: PROUTE.n != 1"; M=$(md5sum $OUT/$t-s6-f360.jpg | cut -c1-32)
  [ "$M" != "$REF6" ] && echo "$t: s6 f360 md5 $M != reference (moved)" || echo "FAIL $t: s6 f360 md5 = reference (the parameter route moved nothing)"
done
[ "$(md5sum $OUT/param-lo-s6-f360.jpg | cut -c1-32)" != "$(md5sum $OUT/param-hi-s6-f360.jpg | cut -c1-32)" ] && echo "param lo != hi on $P" || echo "FAIL param lo == hi on $P"
R=$(CLOCK=1 node tools/cdp.js 'test&scene=6' "[{\"until\":\"window.CARD\"},{\"key\":\"p\"},{\"until\":\"window.__FRAME>=120\"},{\"eval\":\"var s=document.getElementById('pe-psrc-feigen-$P');s.value='centroid';s.dispatchEvent(new Event('change'));1\"},{\"until\":\"window.__FRAME>=126\"},{\"eval\":\"'SET '+CARD.PROUTES.feigen.$P.src+' n '+CARD.PROUTE.n\"},{\"eval\":\"document.getElementById('pe-prst-feigen-$P').click();document.getElementById('pe-phi-feigen-$P').click();1\"},{\"until\":\"window.__FRAME>=140\"},{\"eval\":\"'PREVIEW f140 '+CARD.PROUTES.feigen.$P.src+' c '+CARD.PROUTES.feigen.$P.c\"},{\"until\":\"window.__FRAME>=300\"},{\"eval\":\"'PREVIEW f300 n '+CARD.PROUTE.n+' store '+localStorage.getItem('ew.routes.v1')\"},{\"shot\":\"panel-params-s6-f300\"}]" | grep EVAL | sed 's/.*=> //' | tr -d '"'); echo "$R" | grep -q "SET centroid n 1" && echo "$R" | grep -q "PREVIEW f140 const c $HI" && echo "$R" | grep -q "PREVIEW f300 n 0 store null" && echo "panel params: set by select, hi preview for 2 s of ticks, back, storage null" || echo "FAIL panel params: $R"
echo "== torus2"         # v0.7: TORUS2 (id 3 since §37, TORUS's bid; torus-v1 is id 7 forced-only): its own f360/f840 md5s against tools/accept/v0.7/scene-md5-v07.txt; the interior is lit (tools/lum.py: centre 20 % of the frame vs the 60–90 % rim annulus, ratio >= .35 and centre >= .4 at f360); the pinned kick train (hooks.train) puts four bumps per ring evenly spaced for 4x4 and unevenly for sync (positions from hooks.info, de-duplicated: a wave a bar old sits where a new one launches — one ring per bar); a param route moves the s7 md5; ids 0–6 unchanged is the "== params" identity diff above
R7=tools/accept/v0.7/scene-md5-v07.txt
for f in 360 840; do M=$(md5sum $OUT/t2-s3-f$f.jpg 2>/dev/null | cut -c1-32); REF=$(grep "s3-f$f" $R7 | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=3' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"t2-s3-f$f\"},{\"eval\":\"'s3 f$f errs '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())\"}]" | grep EVAL | sed 's/.*=> //'
  M=$(md5sum $OUT/t2-s3-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "torus2 f$f md5 $M = reference" || echo "FAIL torus2 f$f md5 $M != reference $REF"
done
L=$(python3 tools/lum.py $OUT/t2-s3-f360.jpg); echo "$L"; echo "$L" | awk '{c=$3; r=$7; if (c>=0.4 && r>=0.35) print "torus2 interior lit: centre " c " ratio " r; else print "FAIL torus2 interior dark: centre " c " ratio " r}'
for t in 4x4 sync; do
  CLOCK=1 node tools/cdp.js 'test&scene=3' "[{\"until\":\"window.CARD\"},{\"eval\":\"CARD.REG[3].scene.hooks.train('$t');CARD.REG[3].scene.hooks.fib(1);1\"},{\"until\":\"window.__FRAME>=360\"},{\"shot\":\"t2-train-$t\"},{\"eval\":\"var p=JSON.parse(CARD.REG[3].scene.hooks.info()).kick.filter(function(x,i,a){return i===0||x!==a[i-1]});var d=p.map(function(x,i){return +(((p[(i+1)%p.length]-x)+1)%1).toFixed(3)});'TRAIN $t n '+p.length+' pos '+JSON.stringify(p)+' gaps '+JSON.stringify(d)+' even '+d.every(function(g){return Math.abs(g-0.25)<0.03})\"}]" | grep EVAL | sed 's/.*=> //' | tee $OUT/t2-train-$t.txt | sed 's/^"//;s/"$//'
done
grep -q "even true" $OUT/t2-train-4x4.txt && grep -q "even false" $OUT/t2-train-sync.txt && echo "torus2 train: 4x4 evenly spaced, sync not" || echo "FAIL torus2 train: 4x4 $(grep -o 'even [a-z]*' $OUT/t2-train-4x4.txt) sync $(grep -o 'even [a-z]*' $OUT/t2-train-sync.txt)"
CLOCK=1 node tools/cdp.js 'test&scene=3&param=torus2.morph=c:1' '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"t2-par-morph1-s3-f360"},{"eval":"'"'"'n '"'"'+CARD.PROUTE.n+'"'"' p '"'"'+JSON.stringify(CARD.paramsOf('"'"'torus2'"'"'))"}]' | grep EVAL | sed 's/.*=> //'
[ "$(md5sum $OUT/t2-par-morph1-s3-f360.jpg | cut -c1-32)" != "$(grep s3-f360 $R7 | cut -c1-32)" ] && echo "torus2 param morph=1 moves the f360 md5" || echo "FAIL torus2 param morph=1 moved nothing"
python3 tools/montage.py $OUT/montage-torus2.jpg 2 $OUT/s7-t6.jpg $OUT/s3-t6.jpg $OUT/s7-t14.jpg $OUT/s3-t14.jpg $OUT/t2-train-4x4.jpg $OUT/t2-train-sync.jpg 2>/dev/null && echo "montage $OUT/montage-torus2.jpg"
echo "== nav2"           # v0.8: NAV2 (id 8, forced-only, score 0 — DECISIONS §39): its own f360/f840 md5s against tools/accept/v0.8/scene-md5-v08.txt, the &still=1 four against nav2-still-md5.txt (every NAV2-only uniform at its IEEE-identity rest), the two node tests, and the continuity monitor over 30 s with NAV2's state injected (max must stay under 0.06: every non-cut frame moves cPath by <= V_MAX*dt by construction)
R8=tools/accept/v0.8/scene-md5-v08.txt
for f in 360 840; do REF=$(grep "s8-f$f" $R8 | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=8' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"n2-s8-f$f\"},{\"eval\":\"'s8 f$f errs '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())+' '+CARD.REG[8].scene.hud().slice(0,60)\"}]" | grep EVAL | sed 's/.*=> //'
  M=$(md5sum $OUT/n2-s8-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "nav2 f$f md5 $M = reference" || echo "FAIL nav2 f$f md5 $M != reference $REF"
done
for f in 360 480 720 840; do REF=$(grep "still-f$f" tools/accept/v0.8/nav2-still-md5.txt | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=8&still=1' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"n2-still-s8-f$f\"}]" > /dev/null
  M=$(md5sum $OUT/n2-still-s8-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "nav2 still f$f md5 $M = reference" || echo "FAIL nav2 still f$f md5 $M != reference $REF"
done
node tools/test_field.js | tail -1; node tools/test_nav2.js | tail -1
MON=$(grep -v '^//' tools/monitor.js | tr '\n' ' ' | sed 's/"/\\"/g')
R=$(node tools/cdp.js 'test&fake=0&scene=8' "[{\"until\":\"window.CARD\"},{\"wait\":1500},{\"eval\":\"CARD.NAV=CARD.REG[8].scene.state;$MON;'ok'\"},{\"wait\":30000},{\"eval\":\"'MON8 '+JSON.stringify({n:MON.n,fast:MON.fast,max:+MON.max.toFixed(4),viol:MON.viol})\"}]" | grep MON8 | sed 's/.*=> //' | tr -d '"'); echo "$R"
echo "$R" | grep -q 'viol:\[\]' && echo "nav2 monitor clean" || echo "FAIL nav2 monitor: $R"
python3 tools/montage.py $OUT/montage-nav2.jpg 2 $OUT/n2-s8-f360.jpg $OUT/n2-s8-f840.jpg $OUT/n2-still-s8-f360.jpg $OUT/n2-still-s8-f840.jpg 2>/dev/null && echo "montage $OUT/montage-nav2.jpg"
echo "== polytope"       # v0.9: POLYTOPE (id 5, modified in place — DECISIONS §41): its own f360/f840 md5s against tools/accept/v0.9/scene-md5-v09.txt (= the v0.8 list with s5 re-based; ids 0–4, 6–8 are the "== scenes" identity); the pinned bass train (hooks.train) puts four bumps per edge evenly spaced for 4x4 and unevenly for sync (positions from hooks.info().bass.pos, de-duplicated); the key pair hooks.key(0,0) vs (7,1) differ (warm vs cool, the wheel turned); a param route (groove=c:0) moves the s5 md5; the node test
R9=tools/accept/v0.9/scene-md5-v09.txt
for f in 360 840; do REF=$(grep "s5-f$f" $R9 | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=5' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"pd-s5-f$f\"},{\"eval\":\"'s5 f$f errs '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())+' '+CARD.REG[5].scene.hud()\"}]" | grep EVAL | sed 's/.*=> //'
  M=$(md5sum $OUT/pd-s5-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "polytope f$f md5 $M = reference" || echo "FAIL polytope f$f md5 $M != reference $REF"
done
for t in 4x4 sync; do
  CLOCK=1 node tools/cdp.js 'test&scene=5' "[{\"until\":\"window.CARD\"},{\"eval\":\"CARD.REG[5].scene.hooks.train('$t');1\"},{\"until\":\"window.__FRAME>=360\"},{\"shot\":\"pd-train-$t\"},{\"eval\":\"var i=CARD.REG[5].scene.hooks.info();if(typeof i==='string')i=JSON.parse(i);var p=i.bass.pos.filter(function(x,j,a){return j===0||x!==a[j-1]});var d=p.map(function(x,j){return +(((p[(j+1)%p.length]-x)+1)%1).toFixed(3)});'TRAIN $t n '+p.length+' pos '+JSON.stringify(p)+' gaps '+JSON.stringify(d)+' even '+d.every(function(g){return Math.abs(g-0.25)<0.03})\"}]" | grep EVAL | sed 's/.*=> //' | tee $OUT/pd-train-$t.txt | sed 's/^"//;s/"$//'
done
grep -q "even true" $OUT/pd-train-4x4.txt && grep -q "even false" $OUT/pd-train-sync.txt && echo "polytope train: 4x4 evenly spaced, sync not" || echo "FAIL polytope train: 4x4 $(grep -o 'even [a-z]*' $OUT/pd-train-4x4.txt) sync $(grep -o 'even [a-z]*' $OUT/pd-train-sync.txt)"
for k in "0,0" "7,1"; do n=${k/,/-}
  CLOCK=1 node tools/cdp.js 'test&scene=5' "[{\"until\":\"window.CARD\"},{\"eval\":\"CARD.REG[5].scene.hooks.key($k);1\"},{\"until\":\"window.__FRAME>=360\"},{\"shot\":\"pd-key-$n\"}]" > /dev/null
done
[ "$(md5sum $OUT/pd-key-0-0.jpg | cut -c1-32)" != "$(md5sum $OUT/pd-key-7-1.jpg | cut -c1-32)" ] && echo "polytope key pair: C major and G minor differ (warm vs cool, the wheel turned)" || echo "FAIL polytope key pair identical"
CLOCK=1 node tools/cdp.js 'test&scene=5&param=polytope.groove=c:0' '[{"until":"window.CARD"},{"until":"window.__FRAME>=360"},{"shot":"pd-par-groove0-s5-f360"},{"eval":"'"'"'n '"'"'+CARD.PROUTE.n+'"'"' p '"'"'+JSON.stringify(CARD.paramsOf('"'"'polytope'"'"'))"}]' | grep EVAL | sed 's/.*=> //'
[ "$(md5sum $OUT/pd-par-groove0-s5-f360.jpg | cut -c1-32)" != "$(grep s5-f360 $R9 | cut -c1-32)" ] && echo "polytope param groove=0 moves the f360 md5" || echo "FAIL polytope param groove=0 moved nothing"
node tools/test_polytope.js | tail -1
python3 tools/montage.py $OUT/montage-polytope-accept.jpg 2 $OUT/pd-s5-f360.jpg $OUT/pd-s5-f840.jpg $OUT/pd-train-4x4.jpg $OUT/pd-train-sync.jpg $OUT/pd-key-0-0.jpg $OUT/pd-key-7-1.jpg 2>/dev/null && echo "montage $OUT/montage-polytope-accept.jpg"
echo "== gielis"         # v0.14: GIELIS (id 10, forced-only, score 0, no digit key — DECISIONS §47): its own f360/f840 md5s against tools/accept/v0.14/scene-md5-v014.txt, the &still=1 pair against gielis-still-md5.txt (every music-driven uniform at rest: n1 at N1_REST, no waves, no flash/shimmer, morph 0), the node test, the pinned kick train (hooks.train('4x4') puts four bumps per ring at gaps of exactly .25 — positions from hooks.info().kick, doubled because a wave a bar old sits where a new one launches), and the continuity monitor over 30 s with GIELIS's state injected (viol [])
R10=tools/accept/v0.14/scene-md5-v014.txt
for f in 360 840; do REF=$(grep "s10-f$f" $R10 | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=10' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"gi-s10-f$f\"},{\"eval\":\"'s10 f$f errs '+JSON.stringify(CARD.ERRS)+' bad '+JSON.stringify(CARD.nonFinite())+' '+CARD.REG[10].scene.hud().slice(0,70)\"}]" | grep EVAL | sed 's/.*=> //'
  M=$(md5sum $OUT/gi-s10-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "gielis f$f md5 $M = reference" || echo "FAIL gielis f$f md5 $M != reference $REF"
done
for f in 360 840; do REF=$(grep "still-f$f" tools/accept/v0.14/gielis-still-md5.txt | cut -c1-32)
  CLOCK=1 node tools/cdp.js 'test&scene=10&still=1' "[{\"until\":\"window.CARD\"},{\"until\":\"window.__FRAME>=$f\"},{\"shot\":\"gi-still-s10-f$f\"}]" > /dev/null
  M=$(md5sum $OUT/gi-still-s10-f$f.jpg | cut -c1-32); [ "$M" = "$REF" ] && echo "gielis still f$f md5 $M = reference" || echo "FAIL gielis still f$f md5 $M != reference $REF"
done
node tools/test_gielis.js | tail -1
R=$(CLOCK=1 node tools/cdp.js 'test&scene=10&pinch=6' "[{\"until\":\"window.CARD\"},{\"eval\":\"CARD.REG[10].scene.hooks.train('4x4')\"},{\"until\":\"window.__FRAME>=480\"},{\"shot\":\"gi-train-4x4-f480\"},{\"eval\":\"'TRAIN '+JSON.stringify(JSON.parse(CARD.REG[10].scene.hooks.info()).kick)\"}]" | grep TRAIN | sed 's/.*=> //' | tr -d '"'); echo "$R"
python3 -c "
import json,sys; p=sorted(set(json.loads('$R'.split('TRAIN ')[1]))); g=[round(p[i+1]-p[i],3) for i in range(len(p)-1)]
print('gielis train 4x4 gaps',g, 'ok' if len(p)==4 and all(abs(x-.25)<.01 for x in g) else 'FAIL')"
MON=$(grep -v '^//' tools/monitor.js | tr '\n' ' ' | sed 's/"/\\"/g')
R=$(node tools/cdp.js 'test&fake=0&scene=10' "[{\"until\":\"window.CARD\"},{\"wait\":1500},{\"eval\":\"CARD.NAV=CARD.REG[10].scene.state;$MON;'ok'\"},{\"wait\":30000},{\"eval\":\"'MON10 '+JSON.stringify({n:MON.n,fast:MON.fast,max:+MON.max.toFixed(4),viol:MON.viol})\"}]" | grep MON10 | sed 's/.*=> //' | tr -d '"\\'); echo "$R"
echo "$R" | grep -q 'viol:\[\]' && echo "gielis monitor clean" || echo "FAIL gielis monitor: $R"
python3 tools/montage.py $OUT/montage-gielis.jpg 2 $OUT/gi-s10-f360.jpg $OUT/gi-s10-f840.jpg $OUT/gi-still-s10-f360.jpg $OUT/gi-train-4x4-f480.jpg 2>/dev/null && echo "montage $OUT/montage-gielis.jpg"
echo "== landing"        # v0.8.1: the scene tiles on the real path (steps in tools/landing-steps.json, HARNESS "Landing tiles"): one tile per `card` scene + DIRECTOR, thumbnails loaded (480 wide), a tile click previews on the muted demo with the card in peek, the director tile releases, the demo link starts the show and keeps the forced scene
R=$(GPU=1 node tools/cdp.js real "$(cat tools/landing-steps.json)"); echo "$R" | grep EVAL | sed 's/.*=> //'
echo "$R" | grep -q "TILES 6 imgs 480,480,480,480,480,480" && echo "landing: 6 tiles, 6 thumbnails" || echo "FAIL landing tiles/thumbnails"
echo "$R" | grep -q "PEEK true 6 6 demo 0 peek" && echo "landing: FEIGEN tile previews on the muted demo in peek" || echo "FAIL landing peek"
echo "$R" | grep -q "DIRECTOR -1" && echo "$R" | grep -q "START demo false 3 hide true \[\]" && echo "landing: director tile releases, the demo link starts on the forced scene" || echo "FAIL landing start path"
MOBILE=1 GPU=1 node tools/cdp.js real '[{"until":"window.CARD"},{"wait":1500},{"shot":"landing-mobile"}]' >/dev/null 2>&1 && echo "landing-mobile.jpg for the eyes"
echo "== help"           # v0.2 §12: two shots with the help open (NAV f120, TORUS f360 — the fake timeline's first switch is at 233), the cast scrolled, coverage by eval, ticks hidden/open, the real path with the help opened and closed
CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"key":"h"},{"until":"window.__FRAME>=120"},{"shot":"help-s0-f120"},{"until":"window.__FRAME>=360"},{"shot":"help-s3-f360"},{"eval":"document.getElementById('"'"'help'"'"').scrollTop=1e5;'"'"'help cast shot scrolled to '"'"'+document.getElementById('"'"'help'"'"').scrollTop"},{"shot":"help-cast"},{"eval":"(function(){var out=[],ok=0,n=0,all=Object.keys(CARD.FEATS).filter(function(k){return CARD.FEATS[k].kind!==\"internal\"}).length,rows=0,uniq=0;for(var i=0;i<CARD.REG.length;i++){var E=CARD.REG[i];if(!E)continue;n++;CARD.goScene(E.id,true);var t=CARD.HELP.rows(true),r=CARD.HELP.rows(),f=E.scene.feats;rows=r.length;uniq=new Set(r).size;if(t.slice().sort().join()===f.slice().sort().join())ok++;else out.push(\"id \"+E.id+\" top!=feats\")}return \"help fields \"+rows+\"/\"+all+\" (unique \"+uniq+\") · top table = feats on \"+ok+\"/\"+n+\" ids\"+(out.length?\" FAIL \"+out.join(\",\"):\"\")})()"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"'
CLOCK=1 node tools/cdp.js 'test' '[{"until":"window.CARD"},{"until":"window.__FRAME>=600"},{"eval":"'"'"'help ticks hidden '"'"'+CARD.HELP.ticks+'"'"' (600 frames, want 0)'"'"'"},{"key":"h"},{"until":"window.__FRAME>=1200"},{"eval":"'"'"'help ticks open '"'"'+CARD.HELP.ticks+'"'"' (600 frames, want 100) errs '"'"'+JSON.stringify(CARD.ERRS)"}]' | grep EVAL | sed 's/.*=> //' | tr -d '"'
R=$(NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"clickSel":"#demo"},{"wait":3000},{"key":"h"},{"wait":1500},{"shot":"help-real"},{"key":"Escape"},{"wait":1500},{"eval":"'"'"'HELP real '"'"'+JSON.stringify({on:CARD.HELP.on,ticks:CARD.HELP.ticks,bad:CARD.nonFinite(),errs:CARD.ERRS})"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions with the help open"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
echo "== real start path"
R=$(NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"shot":"real-landing"},{"clickSel":"#demo"},{"wait":4000},{"eval":"'"'"'REAL '"'"'+JSON.stringify({mode:CARD.ENGINE.AU.mode,bad:CARD.nonFinite(),errs:CARD.ERRS,glerr:CARD.glerr})"},{"shot":"real-4s"},{"wait":20000},{"eval":"'"'"'REAL24 '"'"'+JSON.stringify({bad:CARD.nonFinite(),errs:CARD.ERRS,switched:CARD.SC.hist.length>1})"},{"shot":"real-24s"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
echo "== bundle";        node tools/bundle.js && R=$(FILE=$PWD/dist/retinarave.html NOAUTO=1 node tools/cdp.js 'real' '[{"wait":1500},{"clickSel":"#demo"},{"wait":3000},{"key":"h"},{"wait":1500},{"key":"Escape"},{"wait":25500},{"eval":"'"'"'BUNDLE 30s '"'"'+JSON.stringify({bad:CARD.nonFinite(),errs:CARD.ERRS,mode:CARD.ENGINE.AU.mode,hop:CARD.ENGINE.tex.hop,switched:CARD.SC.hist.length>1,help:[CARD.HELP.on,CARD.HELP.ticks]})"}]'); echo "$R" | grep EVAL | sed 's/.*=> //'; N=$(echo "$R" | grep -c '^\[EXC\]'); [ "$N" = 0 ] && echo "exceptions 0" || { echo "FAIL $N uncaught exceptions in the bundle"; echo "$R" | grep '^\[EXC\]' | head -1 | cut -c1-300; }
python3 tools/montage.py $OUT/montage-scenes.jpg 2 $OUT/s*-t6.jpg $OUT/s*-t14.jpg 2>/dev/null && echo "montage $OUT/montage-scenes.jpg"
