// Regenerates the MS vocabulary appendix in docs/CONTRACTS.md from assets/engine/feats.js (between the markers).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { FEATS } = await import(path.join(ROOT, 'assets/engine/feats.js'));
const rows = Object.entries(FEATS).filter(([, f]) => f.kind !== 'internal')
  .map(([k, f]) => `| \`${k}\` | ${f.kind} | ${f.eli5} | ${f.drives} |`);
const body = `<!-- FEATS:begin (generated by node tools/feats-doc.js — do not edit by hand) -->
| field | kind | what it is | what it drives |
|---|---|---|---|
${rows.join('\n')}
<!-- FEATS:end -->`;
const p = path.join(ROOT, 'docs/CONTRACTS.md');
const s = fs.readFileSync(p, 'utf8');
const out = s.replace(/<!-- FEATS:begin[\s\S]*?<!-- FEATS:end -->/, body);
if (out === s && !s.includes('FEATS:begin')) throw new Error('markers not found in CONTRACTS.md');
fs.writeFileSync(p, out);
console.log('feats appendix:', rows.length, 'fields');
